### ISSUE TITLE
Example throws NPE

### ISSUE THREAD

**Issue by beders** [threatgrid/naga#120]
I was cloning the repository and ran the following:

```
% lein run example_data/family.lg        
WARNING: requiring-resolve already refers to: #'clojure.core/requiring-resolve in namespace: datomic.common, being replaced by: #'datomic.common/requiring-resolve
Syntax error (NullPointerException) compiling at (/private/var/folders/51/w0wx0v8171s3_vgr_n29pw700000gn/T/form-init10978326560933034686.clj:1:126).
null
```

My env:
 lein -version
Leiningen 2.9.1 on Java 11.0.3 OpenJDK 64-Bit Server VM

Unclear how I can debug this. Any ideas?

**Comment by quoll** [comment]
This was an issue with new query capabilities in Asami not being propagated through correctly. Can you please try again and let me know?

**Comment by quoll** [comment]
Also, the requiring-resolve issue is fixed with the latest Datomic, but that isn't available anywhere on Maven. It's been months, so I'm thinking there must be a reason why it wasn't put up there
